// <auto-generated />
using System;
using AziendeDati.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AziendeDati.Infrastructure.Migrations
{
    [DbContext(typeof(AziendeDbContext))]
    [Migration("20260702101345_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AziendeDati.Domain.Entities.Azienda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRegistrazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartitaIva")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("P_IVA");

                    b.Property<string>("RagioneSociale")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("RAG_SOC");

                    b.HasKey("Id");

                    b.HasIndex("PartitaIva")
                        .IsUnique();

                    b.ToTable("Aziende", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataRegistrazione = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PartitaIva = "01234567890",
                            RagioneSociale = "ACME S.p.A."
                        },
                        new
                        {
                            Id = 2,
                            DataRegistrazione = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PartitaIva = "09876543210",
                            RagioneSociale = "Globex S.r.l."
                        });
                });

            modelBuilder.Entity("AziendeDati.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descrizione")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Categorie", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descrizione = "Temperature rilevate dai sensori, in gradi Celsius",
                            Nome = "Temperatura"
                        },
                        new
                        {
                            Id = 2,
                            Descrizione = "Pressioni di esercizio degli impianti, in bar",
                            Nome = "Pressione"
                        },
                        new
                        {
                            Id = 3,
                            Descrizione = "Umidità relativa ambientale, in percentuale",
                            Nome = "Umidità"
                        },
                        new
                        {
                            Id = 4,
                            Descrizione = "Consumi elettrici degli impianti, in kWh",
                            Nome = "Consumo energetico"
                        });
                });

            modelBuilder.Entity("AziendeDati.Domain.Entities.Dato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AziendaId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AziendaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Dati", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AziendaId = 1,
                            CategoriaId = 1,
                            Timestamp = new DateTime(2025, 5, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 21.50m
                        },
                        new
                        {
                            Id = 2,
                            AziendaId = 1,
                            CategoriaId = 1,
                            Timestamp = new DateTime(2025, 5, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 22.30m
                        },
                        new
                        {
                            Id = 3,
                            AziendaId = 1,
                            CategoriaId = 2,
                            Timestamp = new DateTime(2025, 5, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1.75m
                        },
                        new
                        {
                            Id = 4,
                            AziendaId = 1,
                            CategoriaId = 3,
                            Timestamp = new DateTime(2025, 5, 11, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 45.00m
                        },
                        new
                        {
                            Id = 5,
                            AziendaId = 1,
                            CategoriaId = 4,
                            Timestamp = new DateTime(2025, 5, 11, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 120.40m
                        },
                        new
                        {
                            Id = 6,
                            AziendaId = 2,
                            CategoriaId = 1,
                            Timestamp = new DateTime(2025, 5, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 19.80m
                        },
                        new
                        {
                            Id = 7,
                            AziendaId = 2,
                            CategoriaId = 2,
                            Timestamp = new DateTime(2025, 5, 10, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Value = 2.10m
                        },
                        new
                        {
                            Id = 8,
                            AziendaId = 2,
                            CategoriaId = 3,
                            Timestamp = new DateTime(2025, 5, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 55.20m
                        },
                        new
                        {
                            Id = 9,
                            AziendaId = 2,
                            CategoriaId = 4,
                            Timestamp = new DateTime(2025, 5, 11, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 98.75m
                        },
                        new
                        {
                            Id = 10,
                            AziendaId = 2,
                            CategoriaId = 1,
                            Timestamp = new DateTime(2025, 5, 12, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 23.10m
                        });
                });

            modelBuilder.Entity("AziendeDati.Domain.Entities.Ordine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AziendaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AziendaId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Ordini", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AziendaId = 1,
                            Data = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = "ORD-2025-001"
                        },
                        new
                        {
                            Id = 2,
                            AziendaId = 2,
                            Data = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Numero = "ORD-2025-002"
                        });
                });

            modelBuilder.Entity("AziendeDati.Domain.Entities.RigaOrdine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrdineId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrezzoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantita")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("OrdineId");

                    b.ToTable("RigheOrdine", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descrizione = "Sensore temperatura TX-100",
                            OrdineId = 1,
                            PrezzoUnitario = 79.90m,
                            Quantita = 5
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Descrizione = "Sensore pressione PX-20",
                            OrdineId = 1,
                            PrezzoUnitario = 149.50m,
                            Quantita = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            Descrizione = "Igrometro ambientale HX-5",
                            OrdineId = 2,
                            PrezzoUnitario = 59.00m,
                            Quantita = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 4,
                            Descrizione = "Contatore energia EX-1",
                            OrdineId = 2,
                            PrezzoUnitario = 320.00m,
                            Quantita = 1
                        });
                });

            modelBuilder.Entity("AziendeDati.Domain.Entities.Ruolo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Ruoli", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "data.company.owner"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "data.company.reader"
                        });
                });

            modelBuilder.Entity("AziendeDati.Domain.Entities.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Attivo")
                        .HasColumnType("bit");

                    b.Property<int>("AziendaId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("RuoloId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AziendaId");

                    b.HasIndex("RuoloId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Utenti", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attivo = true,
                            AziendaId = 1,
                            Email = "mario.rossi@acme.it",
                            RuoloId = 1,
                            Username = "mario.rossi"
                        },
                        new
                        {
                            Id = 2,
                            Attivo = true,
                            AziendaId = 1,
                            Email = "laura.bianchi@acme.it",
                            RuoloId = 2,
                            Username = "laura.bianchi"
                        },
                        new
                        {
                            Id = 3,
                            Attivo = true,
                            AziendaId = 2,
                            Email = "giulia.verdi@globex.it",
                            RuoloId = 1,
                            Username = "giulia.verdi"
                        },
                        new
                        {
                            Id = 4,
                            Attivo = true,
                            AziendaId = 2,
                            Email = "paolo.neri@globex.it",
                            RuoloId = 2,
                            Username = "paolo.neri"
                        });
                });

            modelBuilder.Entity("AziendeDati.Domain.Entities.Dato", b =>
                {
                    b.HasOne("AziendeDati.Domain.Entities.Azienda", "Azienda")
                        .WithMany("Dati")
                        .HasForeignKey("AziendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AziendeDati.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Dati")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Azienda");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("AziendeDati.Domain.Entities.Ordine", b =>
                {
                    b.HasOne("AziendeDati.Domain.Entities.Azienda", "Azienda")
                        .WithMany("Ordini")
                        .HasForeignKey("AziendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Azienda");
                });

            modelBuilder.Entity("AziendeDati.Domain.Entities.RigaOrdine", b =>
                {
                    b.HasOne("AziendeDati.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AziendeDati.Domain.Entities.Ordine", "Ordine")
                        .WithMany("Righe")
                        .HasForeignKey("OrdineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Ordine");
                });

            modelBuilder.Entity("AziendeDati.Domain.Entities.Utente", b =>
                {
                    b.HasOne("AziendeDati.Domain.Entities.Azienda", "Azienda")
                        .WithMany("Utenti")
                        .HasForeignKey("AziendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AziendeDati.Domain.Entities.Ruolo", "Ruolo")
                        .WithMany("Utenti")
                        .HasForeignKey("RuoloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Azienda");

                    b.Navigation("Ruolo");
                });

            modelBuilder.Entity("AziendeDati.Domain.Entities.Azienda", b =>
                {
                    b.Navigation("Dati");

                    b.Navigation("Ordini");

                    b.Navigation("Utenti");
                });

            modelBuilder.Entity("AziendeDati.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Dati");
                });

            modelBuilder.Entity("AziendeDati.Domain.Entities.Ordine", b =>
                {
                    b.Navigation("Righe");
                });

            modelBuilder.Entity("AziendeDati.Domain.Entities.Ruolo", b =>
                {
                    b.Navigation("Utenti");
                });
#pragma warning restore 612, 618
        }
    }
}
